# Generated by Django 3.2.4 on 2021-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.SlugField(max_length=7, unique=True),
        ),
    ]
